
import Navbar from './components/Navbar/Navbar'
import Modal from './components/modals/Modal'
import ClientOnly from './components/ClientOnly'

import './globals.css'

export const metadata = {
  title: 'My Site Aribnb',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-smiley'>
        <ClientOnly>
          <Modal actionLabel='提交' title='登录' isOpen/>
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
